# Generated by Django 5.0.1 on 2024-01-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_snippet_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags_nom', models.CharField(max_length=50)),
                ('tags_ajout', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('snippets', models.ManyToManyField(to='gestion.snippet')),
            ],
        ),
    ]
