# Generated by Django 5.0.1 on 2024-01-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_snippet_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='snippet_nom',
            new_name='nom',
        ),
        migrations.AlterField(
            model_name='snippet',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('snippets', models.ManyToManyField(to='gestion.snippet')),
            ],
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
