# Generated by Django 5.0.1 on 2024-01-29 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_rename_snippet_nom_snippet_nom_alter_snippet_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Langage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_ajout', models.DateTimeField(verbose_name="date d'ajout")),
            ],
        ),
        migrations.AddField(
            model_name='snippet',
            name='langage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.langage'),
        ),
    ]
