# Generated by Django 5.0.1 on 2024-01-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_langage_snippet_langage'),
    ]

    operations = [
        migrations.AddField(
            model_name='langage',
            name='nomCodeMirror',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='langage',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout"),
        ),
    ]
