# Generated by Django 5.0.1 on 2024-02-26 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_snippet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='date_maj',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date de modificafion'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='statut',
            field=models.BooleanField(default=False, verbose_name='Public'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='userpermission',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='langage',
            name='nomCodeMirror',
            field=models.CharField(help_text='Nom reconnu pour mettre en surbrillance le code en fonction du language pour ajouter un snippet', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout"),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='slug',
            field=models.SlugField(help_text='Le nom du snippet sans espace et sans accents (pour les urls)', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='createur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GroupTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('tags', models.ManyToManyField(to='gestion.tag')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
