"""
Django settings for snippet project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v+8$0$f9@^4%b190um6m-+x^wu=qxb688qs_kol1np)$@$sz=$'
if os.environ.get("DJANGO_SECRET_KEY") :
    SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')


# SECURITY WARNING: don't run with debug turned on in production!
if os.environ.get("NGINX_SERVER_NAME") :
    BASE_URL = 'https://' + os.environ.get("NGINX_SERVER_NAME")
    DEBUG = False
    
else :
    BASE_URL = 'http://localhost:8000'
    DEBUG = True



ALLOWED_HOSTS = []
ALLOWED_HOSTS.append(os.environ.get("NGINX_SERVER_NAME",'localhost'))

STATIC_ROOT = BASE_DIR / 'static'
CSRF_TRUSTED_ORIGINS = []
if os.environ.get("NGINX_SERVER_NAME"):
    CSRF_TRUSTED_ORIGINS.append('https://' + os.environ.get("NGINX_SERVER_NAME"))

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles', 
    'django.contrib.admindocs', 
    'gestion.apps.GestionConfig',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.gitlab',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
]
GITLAB_URL = os.environ.get("GITLAB_URL", None)
GITLAB_SECRET = os.environ.get("GITLAB_SECRET", None)
GITLAB_CLIENT_ID = os.environ.get("GITLAB_CLIENT_ID", None)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
LOGIN_REDIRECT_URL = "/"
if GITLAB_URL is not None :
    ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"
    SOCIALACCOUNT_PROVIDERS = {
    "gitlab": {
        "SCOPE": ["read_user"],
        "APPS": [
            {
                "client_id": GITLAB_CLIENT_ID,
                "secret": GITLAB_SECRET,
                "settings": {
                    "gitlab_url": GITLAB_URL,
                }
            }
        ]
    },
}


ROOT_URLCONF = 'snippet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'snippet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
LOGIN_URL = "/connexion/"

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
AUTH_USER_MODEL = 'gestion.User'

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
